
    !byte %........
    !byte %#####.##
    !byte %#####.##
    !byte %#####.##
    !byte %........
    !byte %##.#####
    !byte %##.#####
    !byte %##.#####
    
    !byte %.#####..
    !byte %....#...
    !byte %...#....
    !byte %..#.....
    !byte %....#...
    !byte %...#....
    !byte %..#.....
    !byte %.#####..
    
    !byte %.#####..
    !byte %...#....
    !byte %..#.....
    !byte %....#...
    !byte %...#....
    !byte %..#.....
    !byte %....#...
    !byte %.#####..
    
    !byte %.#####..
    !byte %..#.....
    !byte %....#...
    !byte %...#....
    !byte %..#.....
    !byte %....#...
    !byte %...#....
    !byte %.#####..
    
    !byte %.#....#.
    !byte %.#....#.
    !byte %.#....#.
    !byte %.#....#.
    !byte %.#....#.
    !byte %.#....#.
    !byte %.#....#.
    !byte %.#....#.
    
    !byte %........
    !byte %########
    !byte %........
    !byte %........
    !byte %........
    !byte %........
    !byte %########
    !byte %........
    
    !byte %........
    !byte %...#####
    !byte %..#.....
    !byte %.#......
    !byte %.#......
    !byte %.#......
    !byte %.#.....#
    !byte %.#....#.
    
    !byte %........
    !byte %#####...
    !byte %.....#..
    !byte %......#.
    !byte %......#.
    !byte %......#.
    !byte %#.....#.
    !byte %.#....#.

    !byte %.#....#.
    !byte %.#.....#
    !byte %.#......
    !byte %.#......
    !byte %.#......
    !byte %..#.....
    !byte %...#####
    !byte %........
        
    !byte %.#....#.
    !byte %#.....#.
    !byte %......#.
    !byte %......#.
    !byte %......#.
    !byte %.....#..
    !byte %#####...
    !byte %........
    
    ;-- the following tiles will be converted into sprites
    ;-- at runtime (see sprites.asm for explanation)
    
    !byte %...##...
    !byte %...##...
    !byte %...#....
    !byte %..####..
    !byte %.#.##.#.
    !byte %...##...
    !byte %..#..#..
    !byte %.#....#.
    
    !byte %...##...
    !byte %...##...
    !byte %...#....
    !byte %..####..
    !byte %..####..
    !byte %...##...
    !byte %...#.#..
    !byte %..#..#..
    
    !byte %...##...
    !byte %...##...
    !byte %...#....
    !byte %...##...
    !byte %...##...
    !byte %...##...
    !byte %...##...
    !byte %...###..
    
    !byte %...##...
    !byte %...##...
    !byte %...#....
    !byte %..####..
    !byte %..####..
    !byte %...##...
    !byte %..#.#...
    !byte %..#..#..
    
    !byte %........
    !byte %...#....
    !byte %..#..#..
    !byte %....#...
    !byte %...#....
    !byte %..#..#..
    !byte %....#...
    !byte %........
    
    !byte %........
    !byte %..#..#..
    !byte %....#...
    !byte %...#....
    !byte %..#..#..
    !byte %....#...
    !byte %...#....
    !byte %........
    
    !byte %........
    !byte %....#...
    !byte %...#....
    !byte %..#..#..
    !byte %....#...
    !byte %...#....
    !byte %..#..#..
    !byte %........
    
